name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    changelog:
        name: Changelog PR or Release

        if: ${{ github.repository_owner == 'lameuler' }}
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'
                  cache: pip

            - name: Install Python Dependencies
              run: pip install -r requirements.txt

            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  version: npm run version
                  publish: npx changeset publish
                  commit: 'chore: release'
                  title: '[changesets] release'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
